local ls = require 'luasnip'
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s('controller', {
    t 'using Microsoft.AspNetCore.Mvc;',
    t { '', '' },
    t 'namespace ',
    i(1, 'MyApp.Controllers'),
    t { ';', '' },
    t { '', '[ApiController]' },
    t { '', '[Route("api/[controller]")]' },
    t { '', 'public class ' },
    i(2, 'MyController'),
    t ' : ControllerBase',
    t { '', '{' },
    t { '', '    private readonly ' },
    i(3, 'IMyService'),
    t ' _',
    i(4, 'myService'),
    t ';',
    t { '', '' },
    t { '', '    public ' },
    i(5, 'MyController'),
    t '(',
    i(6, 'IMyService'),
    t ' ',
    i(7, 'myService'),
    t ')',
    t { '', '    {' },
    t { '', '        _' },
    i(8, 'myService'),
    t ' = ',
    i(9, 'myService'),
    t ';',
    t { '', '    }' },
    t { '', '' },
    t { '', '    [HttpGet]' },
    t { '', '    public async Task<IActionResult> GetAsync()' },
    t { '', '    {' },
    t { '', '        ' },
    i(0),
    t { '', '    }' },
    t { '', '}' },
  }),
  s('entity', {
    t 'namespace ',
    i(1, 'MyApp.Entities'),
    t { ';', '' },
    t { '', 'public class ' },
    i(2, 'MyEntity'),
    t { '', '{' },
    t { '', '    public Guid Id { get; set; }' },
    t { '', '    public ' },
    i(3, 'string'),
    t ' ',
    i(4, 'Name'),
    t ' { get; set; }',
    t { '', '    public DateTime CreatedAt { get; set; }' },
    t { '', '    public DateTime UpdatedAt { get; set; }' },
    t { '', '    ' },
    i(0),
    t { '', '}' },
  }),
}
